services:
  - type: web
    name: flask-web
    runtime: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tu_base_de_datos_en_railway
          property: connectionString
